# Generated by Django 5.0.1 on 2024-10-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_edition', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=100)),
                ('books_department', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('book_description', models.CharField(max_length=300)),
                ('book_image', models.ImageField(upload_to='books_pictures/')),
                ('book_pdf', models.FileField(upload_to='books_pdf/')),
            ],
        ),
    ]
