# Generated by Django 5.0.1 on 2024-09-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_is_active_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
    ]
